/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iestorredelrey.tiendainformatica.vista;

import com.iestorredelrey.tiendainformatica.dao.ClienteDAO;
import com.iestorredelrey.tiendainformatica.dao.PedidoDAO;
import com.iestorredelrey.tiendainformatica.modelo.Cliente;
import com.iestorredelrey.tiendainformatica.modelo.EstadoPedido;
import com.iestorredelrey.tiendainformatica.modelo.Pedido;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Usuario
 */

public class FrmPedidos extends JFrame {
    private ClienteDAO daoCliente = new ClienteDAO();
    private PedidoDAO daoPedido = new PedidoDAO();
    /**
     * Creates new form FrmClientes
     */
    private double total;
    public FrmPedidos(JFrame ventana) {
        total=0;
        initComponents();
        JTableHeader header = tablaClientes.getTableHeader();
        header.setFont(new Font("Sans Serif", Font.BOLD, 18));//Poner fuente en la cabecera de la tabla
        tablaClientes.setAutoCreateRowSorter(true);
        actualizarTabla();
        actualizarTablaClientes();
        actualizarTotal();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        //Al cerrar la ventana vuelve a la principal
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                ventana.setVisible(true);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnVerPedido = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        lblClientes = new javax.swing.JLabel();
        btnAniadir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("InformaticaJMM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tablaPedidos.setBackground(new java.awt.Color(102, 204, 255));
        tablaPedidos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tablaPedidos.setForeground(new java.awt.Color(0, 0, 0));
        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Estado", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPedidos.setRowHeight(30);
        tablaPedidos.setShowHorizontalLines(true);
        tablaPedidos.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tablaPedidos);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pedidos");

        btnActualizar.setBackground(new java.awt.Color(102, 204, 255));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/subir (1).png"))); // NOI18N
        btnActualizar.setText("Actualizar Estado");
        btnActualizar.setAlignmentY(0.0F);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnVerPedido.setBackground(new java.awt.Color(102, 204, 255));
        btnVerPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnVerPedido.setForeground(new java.awt.Color(0, 0, 0));
        btnVerPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bolsa-de-la-compra (1).png"))); // NOI18N
        btnVerPedido.setText("Ver Pedido");
        btnVerPedido.setAlignmentY(0.0F);
        btnVerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPedidoActionPerformed(evt);
            }
        });

        tablaClientes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setRowHeight(30);
        jScrollPane2.setViewportView(tablaClientes);

        lblClientes.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClientes.setText("Clientes");
        lblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClientesMouseExited(evt);
            }
        });

        btnAniadir.setBackground(new java.awt.Color(102, 204, 255));
        btnAniadir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAniadir.setForeground(new java.awt.Color(0, 0, 0));
        btnAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mas (1).png"))); // NOI18N
        btnAniadir.setText("Añadir Pedido");
        btnAniadir.setAlignmentY(0.0F);
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(102, 204, 255));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/papelera-de-reciclaje (1).png"))); // NOI18N
        btnBorrar.setText("Borrar Pedido");
        btnBorrar.setAlignmentY(0.0F);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(lblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105)
                .addComponent(btnVerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addGap(98, 98, 98)
                .addComponent(lblTotal))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1902, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientes)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblTotal))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnVerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27)
                .addComponent(btnAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int fila = tablaPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningun pedido");
            return;
        }
        int id = (int) tablaPedidos.getValueAt(fila, 0);
        Pedido p = daoPedido.obtenerPorId(id);

        switch (p.getEstadoPedido()) {
            case EstadoPedido.PENDIENTE:
                p.setEstadoPedido(EstadoPedido.ENVIADO);
                break;
            case EstadoPedido.ENVIADO:
                p.setEstadoPedido(EstadoPedido.ENTREGADO);
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Este pedido ya ha sido entregado");
        }
        daoPedido.actualizar(p);
        actualizarTabla();
        JOptionPane.showMessageDialog(rootPane, "Pedido actualizado a: "+p.getEstadoPedido().name());
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnVerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPedidoActionPerformed
        // TODO add your handling code here:
        int fila = tablaPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningun pedido");
            return;
        }
        int id = (int) tablaPedidos.getValueAt(fila, 0);
        Pedido p = daoPedido.obtenerPorId(id);
        FrmVerPedido ventanaVerPedido = new FrmVerPedido(this, p);
        this.setVisible(false);
        ventanaVerPedido.setVisible(true);
    }//GEN-LAST:event_btnVerPedidoActionPerformed

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        // TODO add your handling code here:
        int fila = tablaClientes.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningun cliente");
        }
        int id = (int) tablaClientes.getValueAt(fila, 0);
        Cliente c = daoCliente.obtenerPorId(id);
        daoPedido.insertarPedido(new Pedido(c));
        actualizarTabla();
        actualizarTotal();
        JOptionPane.showMessageDialog(rootPane, "Pedido añadido correctamente");
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int fila = tablaPedidos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningun pedido");
            return;
        }
        int id = (int) tablaPedidos.getValueAt(fila, 0);
        daoPedido.borrar(id);
        actualizarTabla();
        actualizarTotal();
        JOptionPane.showMessageDialog(rootPane, "Pedido eliminado correctamente");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void lblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseClicked
        // TODO add your handling code here:
        FrmClientes ventanaClientes = new FrmClientes(this);
        this.setVisible(false);
        ventanaClientes.setVisible(true);
    }//GEN-LAST:event_lblClientesMouseClicked

    private void lblClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseEntered
        // TODO add your handling code here:
        lblClientes.setForeground(new Color(102,204,255));
    }//GEN-LAST:event_lblClientesMouseEntered

    private void lblClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClientesMouseExited
        // TODO add your handling code here:
        lblClientes.setForeground(Color.black);
    }//GEN-LAST:event_lblClientesMouseExited

    public void actualizarTablaClientes() {
    List<Cliente> clientes = daoCliente.listar();
    if (clientes.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "No hay ningun cliente");
        return;
    }
    DefaultTableModel modelo = (DefaultTableModel) tablaClientes.getModel();
    modelo.setRowCount(0);
    for (Cliente c : clientes) {
        modelo.addRow(new Object[]{c.getId(), c.getNombre()});
    }
}
    public void actualizarTabla() {
    JTableHeader header = tablaPedidos.getTableHeader();
    header.setFont(new Font("Sans Serif", Font.BOLD, 18));//Poner fuente en la cabecera de la tabla
    tablaPedidos.setAutoCreateRowSorter(true);
    List<Pedido> pedidos = daoPedido.listar();
    DefaultTableModel modelotabla = (DefaultTableModel) tablaPedidos.getModel();
    modelotabla.setRowCount(0);
    total = 0;
    for (Pedido p : pedidos) {
        modelotabla.addRow(new Object[]{p.getId(), p.getCliente().getNombre(), p.getEstadoPedido(), daoPedido.calcularTotal(p.getId())});
        total += p.getTotal();//Incrementa el total de pedidos
    }
    actualizarTotal();
}
   
        
    public void actualizarTotal() {
    NumberFormat nf = NumberFormat.getInstance();//Esto es para que salgan los puntos cada dos números
    nf.setMinimumFractionDigits(2);//Y esto para caparlo a dos decimales
    nf.setMaximumFractionDigits(2);

    lblTotal.setText("Total: " + nf.format(daoPedido.calcularTotalTodos()) + "€");//por último lo asignamos al label de total
}
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnVerPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaPedidos;
    // End of variables declaration//GEN-END:variables
}
