/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.iestorredelrey.tiendainformatica.vista;

import com.iestorredelrey.tiendainformatica.dao.LineaPedidoDAO;
import com.iestorredelrey.tiendainformatica.dao.PedidoDAO;
import com.iestorredelrey.tiendainformatica.dao.ProductoDAO;
import com.iestorredelrey.tiendainformatica.modelo.EstadoPedido;
import com.iestorredelrey.tiendainformatica.modelo.LineaPedido;
import com.iestorredelrey.tiendainformatica.modelo.Pedido;
import com.iestorredelrey.tiendainformatica.modelo.Producto;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Usuario
 */

public class FrmVerPedido extends javax.swing.JFrame {
    private LineaPedidoDAO lineaDao = new LineaPedidoDAO();
    private ProductoDAO productoDAO = new ProductoDAO();
    private PedidoDAO pedidoDao = new PedidoDAO();
    
    /**
     * Creates new form FrmClientes
     */
    private Pedido pedido;
    public FrmVerPedido(FrmPedidos ventanaPedidos,Pedido p) {
        initComponents();
        JTableHeader header = tablaProductos.getTableHeader();
        header.setFont(new Font("Sans Serif", Font.BOLD, 18));//Poner fuente en la cabecera de la tabla
        tablaProductos.setAutoCreateRowSorter(true);
        this.pedido=p;
        actualizarTabla();
        actualizarTotal();
        actualizarEstado();
        lblCliente.setText("Cliente: "+pedido.getCliente().getNombre());
        actualizarTablaProductos();
        lblTitulo.setText("Pedido Nº"+pedido.getId());
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        //Al cerrar la ventana vuelve a la principal
        addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e){
                ventanaPedidos.setVisible(true);
                ventanaPedidos.actualizarTabla();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        lblProductos = new javax.swing.JLabel();
        btnAniadir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLineas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        spnCantidad = new javax.swing.JSpinner();
        btnBorrar = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("InformaticaJMM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1915, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        lblTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Pedido Nº");

        tablaProductos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setRowHeight(30);
        jScrollPane2.setViewportView(tablaProductos);

        lblProductos.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductos.setText("Productos");
        lblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductosMouseExited(evt);
            }
        });

        btnAniadir.setBackground(new java.awt.Color(102, 204, 255));
        btnAniadir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAniadir.setForeground(new java.awt.Color(0, 0, 0));
        btnAniadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mas (1).png"))); // NOI18N
        btnAniadir.setText("Añadir Linea");
        btnAniadir.setAlignmentY(0.0F);
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        tablaLineas.setBackground(new java.awt.Color(102, 204, 255));
        tablaLineas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tablaLineas.setForeground(new java.awt.Color(0, 0, 0));
        tablaLineas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Cantidad", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaLineas.setRowHeight(30);
        tablaLineas.setShowHorizontalLines(true);
        tablaLineas.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tablaLineas);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cantidad");

        btnBorrar.setBackground(new java.awt.Color(102, 204, 255));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/papelera-de-reciclaje (1).png"))); // NOI18N
        btnBorrar.setText("Borrar Linea");
        btnBorrar.setAlignmentY(0.0F);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblCliente.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setText("Cliente: ");

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total: ");

        lblEstado.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Estado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1861, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(370, 370, 370)
                                .addComponent(btnBorrar)
                                .addGap(273, 273, 273)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductos)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEstado))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
        int fila = tablaProductos.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ningun producto");
            return;
        }
        int id = (int)tablaProductos.getValueAt(fila, 0);
        Producto producto = productoDAO.obtenerPorId(id);
        int cantidad =(int)spnCantidad.getValue();
        if(cantidad<=0){
            JOptionPane.showMessageDialog(rootPane, "Selecciona la cantidad");
            return;
        }
            if(producto.getStock()<cantidad){
            JOptionPane.showMessageDialog(rootPane,"No hay suficiente stock ("+producto.getStock()+")");
            return;
        }
        if(pedido.getEstadoPedido()==EstadoPedido.ENVIADO||pedido.getEstadoPedido()==EstadoPedido.ENTREGADO){//Si ya ha sido enviado o entregado no puedes modificarlo
            JOptionPane.showMessageDialog(rootPane, "No puedes modificar un pedido que ya ha sido enviado o entregado");
            return;
        }
        producto.setStock(producto.getStock()-cantidad);//Descuenta el stock
        productoDAO.actualizar(producto);//Lo actualiza en la BBDD
        lineaDao.insertarLinea(pedido.getId(), new LineaPedido(producto, cantidad));
        actualizarTabla();
        actualizarTablaProductos();
        actualizarTotal();
        JOptionPane.showMessageDialog(rootPane, "Linea añadida correctamente");
    }//GEN-LAST:event_btnAniadirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        int fila = tablaLineas.getSelectedRow();
        if(fila==-1){
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ninguna línea");
            return;
        }
        int id = (int)tablaLineas.getValueAt(fila, 0);
        if(pedido.getEstadoPedido()==EstadoPedido.ENVIADO||pedido.getEstadoPedido()==EstadoPedido.ENTREGADO){//Si ya ha sido enviado o entregado no puedes modificarlo
            JOptionPane.showMessageDialog(rootPane, "No puedes modificar un pedido que ya ha sido enviado o entregado");
            return;
        }
        LineaPedido lp = lineaDao.obtenerPorId(id);
        Producto p = lp.getProducto();
        p.setStock(p.getStock()+lp.getCantidad());//Devolver el stock al producto
        productoDAO.actualizar(p);//Aplicar cambios en BBDD
        lineaDao.borrarLinea(id);//Borrar la linea
        actualizarTabla();
        actualizarTablaProductos();
        actualizarTotal();
        JOptionPane.showMessageDialog(rootPane, "Linea borrada correctamente");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void lblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseClicked
        // TODO add your handling code here:
        FrmProductos ventanaProductos = new FrmProductos(this);
        this.setVisible(false);
        ventanaProductos.setVisible(true);
    }//GEN-LAST:event_lblProductosMouseClicked

    private void lblProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseEntered
        // TODO add your handling code here:
        lblProductos.setForeground(new Color(102,204,255));
    }//GEN-LAST:event_lblProductosMouseEntered

    private void lblProductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductosMouseExited
        // TODO add your handling code here:
        lblProductos.setForeground(Color.black);
    }//GEN-LAST:event_lblProductosMouseExited

    public void actualizarTablaProductos(){
        List<Producto> productos=productoDAO.listar();
        if(productos.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No hay ningun producto");
            return;
        }
        DefaultTableModel modelo=(DefaultTableModel)tablaProductos.getModel();
        modelo.setRowCount(0);
        for(Producto p:productos){
            modelo.addRow(new Object[]{p.getId(),p.getNombre(),p.getStock()});
        }
    }
    public void actualizarTabla(){

        List<LineaPedido> lineas = lineaDao.listarPorPedido(pedido.getId());
        if(lineas.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Este pedido esta vacío");
        }
        DefaultTableModel modelo = (DefaultTableModel)tablaLineas.getModel();
        modelo.setRowCount(0);
        for(LineaPedido lp:lineas){
            modelo.addRow(new Object[]{lp.getId(),lp.getProducto().getNombre(),lp.getCantidad(),lp.getSubtotal()});
        }
    }
    
    public void actualizarTotal(){
        NumberFormat nf = NumberFormat.getInstance();//Esto es para que salgan los puntos cada dos números
        nf.setMinimumFractionDigits(2);//Y esto para caparlo a dos decimales
        nf.setMaximumFractionDigits(2);

        lblTotal.setText("Total: " + nf.format(pedidoDao.calcularTotal(pedido.getId()))+"€");//por último lo asignamos al label de total
    }
    
    public void actualizarEstado(){
        lblEstado.setText("Estado: "+pedido.getEstadoPedido());
        switch(pedido.getEstadoPedido()){
            case EstadoPedido.PENDIENTE:
                lblEstado.setForeground(Color.red);
                break;
            case EstadoPedido.ENVIADO:
                lblEstado.setForeground(Color.ORANGE);
                break;
            default:
                lblEstado.setForeground(Color.GREEN);       
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tablaLineas;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
